version: '2'

services:
  node-influx-uptimerobot:
    container_name: node-influx-uptimerobot
    hostname: node-influx-uptimerobot
    build:
        context: .
        dockerfile: Dockerfile
    environment:
      APPLICATION_INTERVAL: 10
      UPTIMEROBOT_API_KEY: uxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxx
      UPTIMEROBOT_LOGS_LIMIT: 100
      UPTIMEROBOT_RESPONSE_TIMES_LIMIT: 100
      INFLUX_HOST: influxdb
      INFLUX_PORT: 8086
      INFLUX_PROTOCOL: http
      INFLUX_USERNAME: uptimerobot
      INFLUX_PASSWORD: uptimerobot
      INFLUX_DATABASE: uptimerobot

